- hosts: localhost
  connection: local

  vars:
    remote_debfile: check-mk-raw-1.5.0p16_0.stretch_armhf.deb

  tasks:

    - name: Get current Ansible version on local host
      local_action: command ansible --version
      register: local_ansible_version
    - assert:
        that:
          - "'2.2' in local_ansible_version.stdout"

    - name: cleanup
      command: apt-get clean

    - name: Check if check_mk_raw pakage is in place
      stat: 
        path: /tmp/{{ remote_debfile }}
      register: cmk_debfile

    - name: Download "{{ remote_debfile }}"
      get_url:
        url: https://github.com/chrisss404/check-mk-arm/releases/download/1.5.0p16/{{ remote_debfile }}
        dest: /tmp/{{ remote_debfile }}
      when: cmk_debfile.stat.exists == false

    - name: Try failed install of check_mk_raw to determine deps
      command: dpkg -i /tmp/{{ remote_debfile }}
      ignore_errors: yes

    - name: Install deps
      command: apt-get -f install
